enum Icons {
  ASTERISK = "Asterisk",
  CALENDAR = "Calendar",
  CHECKCIRCLE = "CheckCircle",
  CLOSE = "X",
  INFO = "Info",
  KEYBOARD = "Keyboard",
  MINUS = "Minus",
  PLUS = "Plus",
  MOON = "Moon",
  PLUSCIRCLE = "PlusCircle",
  SUN = "Sun",
  QRCODE = "QrCode",
  USER = "User",
  XCIRCLE = "XCircle",
  DOLLAR = "DollarSign",
  DOWNARROW = "ChevronDown",
  UPARROW = "ChevronUp",
  ARMCHAIR = "Armchair",
  SEARCH = "Search",
  BAGGAGECLAIM = "BaggageClaim",
  MOREVERTICAL = "MoreVertical",
  EYE = "Eye",
  EYEOFF = "EyeOff",
}

export default Icons;
